# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
development:
  adapter: postgresql
  encoding: unicode
  database: blogapp_development
  pool: 5
  username: postgres
  password: admin
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: blogapp_test
  pool: 5
  username: postgres
  password: admin

production:
  adapter: postgresql
  encoding: unicode
  database: blogapp_production
  pool: 5
  username: postgres
  password: admin